// Medical types shared across the app.

export type Sex = 'male' | 'female'

/** 8 triage classes from the BERT model (paper). */
export const TRIAGE_CLASSES = [
  'POZ',
  'Gastroenterology',
  'Hematology',
  'Nephrology',
  'ER',
  'Cardiology',
  'Pulmonology',
  'Hepatology',
] as const

export type TriageClass = (typeof TRIAGE_CLASSES)[number]

/** Lab parameter codes the UI & backend agree on. */
export const LAB_PARAMS = [
  'HGB',
  'CREATININE',
  'PLT',
  'MCV',
  'WBC',
  'ALT',
  'AST',
  'UREA',
] as const

export type LabParam = (typeof LAB_PARAMS)[number]

export type ParameterStatus = 'normal' | 'low' | 'high' | 'critical' | 'unknown'

export interface LabReferenceRange {
  param: LabParam
  label: string
  unit: string
  /** Lower bound of the normal range (inclusive). */
  low: number
  /** Upper bound of the normal range (inclusive). */
  high: number
  /** Below this is "critical low" (life-threatening). */
  criticalLow?: number
  /** Above this is "critical high". */
  criticalHigh?: number
  /** One-line lay explanation of what the parameter measures. */
  description: string
}

export interface LabValue {
  param: LabParam
  value: number | null
  unit?: string
}

export interface PatientInput {
  age: number
  sex: Sex
  values: Record<LabParam, number | null>
  /** Free-text symptoms / context (optional). */
  notes?: string
  /** Date of the blood draw (ISO). */
  collectedAt?: string
}

export interface TriagePrediction {
  class: TriageClass
  probability: number
  /** Calibration confidence (from ECE calibration). Optional. */
  confidence?: number
}

export interface AttentionWeight {
  param: LabParam | string
  weight: number
}

export interface TriageResult {
  predictions: TriagePrediction[]
  attention: AttentionWeight[]
  /** Natural-language explanation (generated by Opus). */
  explanation?: string
  /** Expected Calibration Error at the current threshold. */
  ece?: number
  /** Model version string for audit / demo. */
  modelVersion?: string
}

export type TestUrgency = 'routine' | 'soon' | 'urgent'

export interface SuggestedTest {
  /** Test name, e.g. "Ferritin", "eGFR", "Abdominal ultrasound". */
  name: string
  /** One-sentence justification — why this test would help. */
  reason: string
  urgency: TestUrgency
}

export interface OpusExplanation {
  /** Short, one-paragraph plain-language summary for patients. */
  patientSummary: string
  /** Clinician-facing paragraph with thresholds and differentials. */
  clinicalSummary?: string
  /** Suggested follow-up questions to ask the patient (adaptive interview). */
  followUpQuestions?: string[]
  /** Safety-relevant red flags. */
  redFlags?: string[]
  /** Concrete additional tests the patient should consider. */
  suggestedTests?: SuggestedTest[]
}

export interface TrendDelta {
  param: LabParam
  previous: number | null
  current: number | null
  changePct: number | null
  direction: 'up' | 'down' | 'flat'
}

export type TrendDirection =
  | 'improving'
  | 'stable'
  | 'worsening'
  | 'critical_worsening'

export interface TrendPoint {
  /** ISO date. */
  date: string
  value: number
  status: 'low' | 'normal' | 'high'
}

export interface ParameterTrend {
  parameter: string
  unit: string
  direction: TrendDirection

  slope: number
  r_squared: number
  delta_last_two: number
  delta_pct_last_two: number
  avg_monthly_change: number

  current_value: number
  previous_value: number | null
  min_value: number
  max_value: number
  measurement_count: number
  days_span: number

  is_accelerating: boolean
  crossed_threshold: boolean

  normal_low: number | null
  normal_high: number | null

  points: TrendPoint[]
}

export type AlertSeverity = 'info' | 'warning' | 'urgent' | 'critical'
export type AlertType = 'velocity' | 'threshold' | 'pattern' | 'acceleration'

export interface ClinicalAlert {
  severity: AlertSeverity
  alert_type: AlertType
  parameter: string
  title: string
  description: string
  clinical_significance: string
  recommended_action: string
}

export interface TrendAnalysis {
  deltas: TrendDelta[]
  /** Natural-language interpretation of the trend (Opus). */
  interpretation: string
  urgency: 'low' | 'medium' | 'high'
  /** Full per-parameter trend statistics (linear regression, velocity). */
  trends?: ParameterTrend[]
  /** Clinical alerts (velocity / threshold / pattern). */
  alerts?: ClinicalAlert[]
}

export interface HistoryEntry {
  id: string
  /** ISO timestamp. */
  createdAt: string
  input: PatientInput
  result?: TriageResult
  explanation?: OpusExplanation
}
